name: Clean tempest install

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-qa:
    name: Run QA
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Init composer
        run:  composer init -ns dev --autoload=src

      - name: Require Tempest
        run: composer require tempest/framework:dev-main

      - name: List Installed Dependencies
        run: composer show -D

      - name: Install Tempest
        run: php vendor/bin/tempest install framework --force

      - name: Run Tempest console
        run: php ./tempest
#
#      - name: Install auth
#        run: php ./tempest install auth --force

      - name: Run Tempest Server in the background
        run: php ./tempest serve &

      - name: Try GET request
        run: curl http://localhost:8000
